### ISSUE TITLE
file list needed

### ISSUE THREAD

**Issue by SimLeek** [SimLeek/cse360_text_file_analyzer#4]
there should be a panel on the left with a list of the currently open files
It doesn't have to be a tree.

**Comment by SimLeek** [comment]
I'll work on this. I think I'll just copy-paste most of the tree stuff I had and have it not go through directories. Possibly also make it single threaded, but I found a stackOverflow for updating from different threads if we need it. I don't think we will though. I'll just add files to it from the main/browse class, and start with a single file.

**Comment by SimLeek** [comment]
![image](https://user-images.githubusercontent.com/5911683/32922569-0c2390be-caf0-11e7-810a-77b3942325e8.png)

Done! committing.

**Comment by GitRafaelZamora** [comment]
Awesome!

**Comment by SimLeek** [comment]
Alright, I also made it update when you add new files. It doesn't check the directory constantly like file tree does, so if you modify it outside the program, it won't update, but eh...

I'll mark this complete, and maybe open another issue for actually opening the files.
